---
title: "Interactive "
author: "Group 16"
date: "March 28, 2016"
output: html_document
---
### Introduction:

One of the first challenges we have encountered when we come to New York City for school is to find a place to live. It was not easy - as a newcomer, we don't have much knowledge of the city. We don't know which areas are safe or where to find a nice apartment under our budget constraints. We have no idea about the transportation system or the crowdedness of different areas. At the same time, we need to make a decision on where to live before school starts. There is a gap between not knowing the city and needing the background knowledge to make an informed decision on housing. Even though we can consult our friends in the city or using other resource to find out about the city (such as search the internet or reading the housing information page on Columbia website), we don't have a way to get complete information on the city to systematically evaluate our options. Fortunately, there are many data sets about the city out there, so we can use our data science techniques on available data to visualize the city. As a result, we decided to use publically available data to help new students find a save apartment that best serve their needs. There are many factors that we consider when we search for an apartment:
 
* we want to live in a safe neighborhood
* we want the price to be under our budget constraint
* we want the living condition to be as good as possible
* we want the commute time to school to be short
 
So the top five factors we consider in our project are crime rate, apartment rental price, residential complaints, population density, and transportation. We visualized the data we have on three graphs:
 
First, we have an interactive dot plot where we plot residential complaints, crime rate, and transportation information on a map. We make it an interactive map so that students can choose the kind of information to present on the map. We also list the top five complains and top five crimes under the categories of complains and crimes so that students can visualize a particular crime or complain they care the most about.
 
The dot plot gives us very specific information on each incidence. While it is good for getting to know a particular small region, it may be too specific and could not give us a clear general overview of a region in the larger scale. So we create an interactive heat map. Using color representation, we can easily see the severity of each type of complaints, crime, as well as transportation on the map.

These two interactive maps are intended to give students an overview of the different areas in New York City. When we vaguely narrow down our search to a few safe and nice areas, we want to further narrow down to more specific area. We decide distinct different regions by zip code, which combines representation in both latitude and longitude. So in the last graph, we put all the five factors we care the most on one interactive map - students can adjust the complains level, population density level, convenience in transportation, safety level, and price level on the interface so that the map returns the area via zip code that matches all the criterions.

### Data Source:
We collected the data from NYC OpenData website. The dataset is a collection of 311 service requests from 2010 to present. 311 service line is New York City's main source of government information and non-emergency services. Whether you're a resident, business owner, or visitor, help is just a click, text, or call away. In addition, zillow research data is also utilized. The dataset provide rental and house value in a given region in NYC range from Jan 2015 to Jan 2016.

### Price graph (Trelli):

```{r,warning=FALSE, message= FALSE,echo=FALSE}
library(ggplot2)
library(reshape2)

home_value = read.csv("home_value.csv")
home_value$Price = home_value$Price/1000
rent_value = read.csv("Med_Rent.csv")
data = rbind(home_value,rent_value)

ggplot(data, aes(Room, Price)) +   
  geom_point(aes(color = Type ))+
  facet_wrap(~RegionName, ncol=3)+coord_flip()+
  ggtitle("Comparison of Home Value and Lease")
```

This graph shows the relationship between number of bedrooms one has and the rent or sale price one will pay. As a common sense, we know the price will increase as number of bedrooms increase. This fact is very clear on the graph. What we are really interested in, however, is the increasing rate of the rent or sale price in five different boroughs as one has more bedrooms. As you can see, compared with manhattan, all other four boroughs have slow such increasing rates and some of them even stay the same. For example, if you buy a house in brooklyn, the median price is almost the same for a two, three or even four-bedroom house. Manhattan's such increasing rate, however, is very high regardless of rent or sale price. 

### Heat Map:
We created a heat map that shows the distributions of different types of living considerations as we talked in the introduction part (complain, crime and transportation). In the complaint part,  we selected top 5 complaints in terms of total number and made an interactive plot to show the distribution of complaints in different areas in NYC.  The graph shows the distribution of different types of complaints. We selected 5 most reported complaint types here in the small box at the right corner and the user can choose anyone to visualize. For example, the most reported complaint type here is "heat and hot water" issue and you can see the distribution of this complaint easily on the corresponding heat map. One thing we found interesting is that if you look into the "blocked driveway" complaint, there are much such few complaints in manhattan than other boroughs in NY state, which is kind of counterintuitive because we have more cars in manhattan. We guess the reason behind this is that manhattan's parking violation fee is very high so most people are afraid of this. For the crime and transportation parts, they work the same way as the compliant part.  The user can check the small boxes to see the different heap map under different categories.

### Interactive Dot plot:
This graph has similar UI to the Heat Map. User can check the small boxes to see the different interactive dot plots under different categories. The interactive plot simulates the distribution of different types of complaints as time went by. For example, if user check the crime box, the plot will show the distribution of incidents of crimes as time went by in a specific area. For the  complain section, it contains top 5 complaints from the 311 dataset and represents in the specific region. For the crime section, it provides the top 5 crimes categories in NYC and represents them in the specific region. For the transportation sections, it provides all the possible subway stations in the chosen area. All the results above are represented in a geographical NYC map and the users have more power on the visualization result, which matters them most.



### Result Section:
This section applies all the previous results and provides the best areas that much the expectation from the users. A complain slide bar is provided and users can simply choose their desired level. Same as complain, population is also provided in a slide manner so that users can choose much their expectation. Price is also provided in the similar fashion. On the other hand, we classify transportation and safety into 3 categories. For instances, transportation has convenience, inter-convenience, and inconvenience for users to click on. After all the conditions are setted by the users, region that much the conditions will be display as a heated area in the map. 


### Conclusion:
This project utilizes one of the most powerful visualization tool in R and every display can can be set up by the user desired. In other words, we focus this project on a more user's interaction format rather than a report format. Besides, each conclusion is driven by a data visualization manner instead of traditional statistical model. All in all, it provides a new direction to solve the same problem.
